
import './globals.css';
import '@radix-ui/themes/styles.css';

import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import React from 'react';

import { cn } from '@/lib/utils';

import ReduxProvider from './redux/ReduxProvider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
